name: Android ARMv8a Build with OpenSSH

on:
  push:
    branches:
      - main  # 你可以修改为触发的分支

jobs:
  setup:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境构建

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: 设置 JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Step 3: 安装依赖项
    - name: Install required dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip build-essential git

    # Step 4: 安装 Android NDK r27c
    - name: Download and Install Android NDK r27c
      run: |
        # 下载并解压 Android NDK
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip -O android-ndk-r27c.zip
        unzip android-ndk-r27c.zip -d $HOME/
        export NDK_HOME=$HOME/android-ndk-r27c
        export PATH=$NDK_HOME:$PATH
        echo "NDK Home: $NDK_HOME"

    # Step 5: 获取并编译 OpenSSH
    - name: Clone and Build OpenSSH for Android
      run: |
        # 克隆 OpenSSH 仓库
        git clone https://android.googlesource.com/platform/external/openssh
        cd openssh
        # 设置编译环境并编译 OpenSSH
        export ANDROID_NDK_HOME=$NDK_HOME
        export PATH=$ANDROID_NDK_HOME:$PATH
        ./configure --host=arm-linux-androideabi --with-ndk=$NDK_HOME
        make

    # Step 6: 构建 Android 项目（可选）
    - name: Build Android project
      run: ./gradlew assembleRelease  # 请确保 gradle 设置正确

    # Step 7: 上传构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-build-artifacts
        path: app/build/outputs
