name: NBuild Dropbear for Android ARMv8a

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-dropbear:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Android NDK
      run: |
        # Fetch the latest Android NDK
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip android-ndk-r25c-linux.zip -d $HOME
        export ANDROID_NDK_HOME=$HOME/android-ndk-r25c
        echo "Android NDK set up at $ANDROID_NDK_HOME"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool

    - name: Download and extract Dropbear source
      run: |
        wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2024.86.tar.bz2
        tar -xjf dropbear-2024.86.tar.bz2
        mv dropbear-2024.86 dropbear

    - name: Modify localoptions.h to disable password login and allow root login
      run: |
        cd dropbear
        # Ensure localoptions.h exists
        touch localoptions.h
        # Disable password authentication
        echo "#define DROPBEAR_SVR_PASSWORD_AUTH 0" >> localoptions.h
        echo "#define DROPBEAR_CLI_PASSWORD_AUTH 0" >> localoptions.h
        # Allow root login (not recommended for production)
        echo "#define DROPBEAR_DISABLE_ROOT 0" >> localoptions.h

    - name: Configure Dropbear for ARMv8a
      run: |
        cd dropbear
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        export CC=aarch64-linux-android21-clang
        export AR=aarch64-linux-android-ar
        export AS=aarch64-linux-android-as
        export LD=aarch64-linux-android-ld
        export STRIP=aarch64-linux-android-strip
        ./configure \
          --host=aarch64-linux-android \
          --disable-zlib \
          --disable-lastlog \
          --disable-utmp \
          --disable-wtmp \
          --disable-utmpx

    - name: Compile Dropbear
      run: |
        cd dropbear
        make PROGRAMS="dropbear dropbearkey dropbearconvert scp"

    - name: Package binaries
      run: |
        mkdir output
        cp dropbear/dropbear output/
        cp dropbear/dropbearkey output/
        cp dropbear/scp output/
        cp dropbear/dropbearconvert output/
        tar -czf dropbear-android-armv8a.tar.gz output

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dropbear-android-armv8a
        path: dropbear-android-armv8a.tar.gz
