name: Build Dropbear for Android

on:
  workflow_dispatch:  # 手动触发工作流
    inputs:
      ndk_url:
        description: "NDK 下载地址"
        default: "https://dl.google.com/android/repository/android-ndk-r27c-linux.zip"
        required: true
      dropbear_url:
        description: "Dropbear 下载地址"
        default: "https://matt.ucc.asn.au/dropbear/releases/dropbear-2024.86.tar.bz2"
        required: true

jobs:
  build-dropbear:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Android NDK
      run: |
        mkdir -p $HOME/android-ndk
        curl -L ${{ inputs.ndk_url }} -o ndk.zip
        unzip ndk.zip -d $HOME/android-ndk
        export ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r27c
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
      env:
        ANDROID_NDK_HOME: $HOME/android-ndk

    - name: Download and Prepare Dropbear
      run: |
        mkdir -p $HOME/dropbear
        curl -L ${{ inputs.dropbear_url }} -o dropbear.tar.bz2
        tar -xjf dropbear.tar.bz2 -C $HOME
        mv $HOME/dropbear-2024.86 $HOME/dropbear

        # 修改 localoptions.h 文件，禁用密码认证
        echo '#define DROPBEAR_SVR_PASSWORD_AUTH 0' >> $HOME/dropbear/localoptions.h
        echo '#define DROPBEAR_CLI_PASSWORD_AUTH 0' >> $HOME/dropbear/localoptions.h

    - name: Modify svr-auth.c for Root Login
      run: |
        cd $HOME/dropbear/src
        # 修改 svr-auth.c 强制跳过认证
        sed -i 's/if (auth_check() == DROPBEAR_FAILURE)/if (0)/' svr-auth.c

    - name: Compile Dropbear
      run: |
        cd $HOME/dropbear
        export CC=aarch64-linux-android24-clang
        export CXX=aarch64-linux-android24-clang++
        ./configure --host=aarch64-linux-android --prefix=$HOME/dropbear-build --disable-zlib --disable-shadow
        make -j$(nproc)
        make install

    - name: Upload Compiled Dropbear
      uses: actions/upload-artifact@v3
      with:
        name: dropbear-android-armv8a
        path: $HOME/dropbear-build
