name: Build libssh for Android armv8a

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/jdk-11
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk-r27c

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Download and extract Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip android-ndk-r27c-linux.zip -d ${{ github.workspace }}

    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake

    - name: Download libssh source
      run: |
        wget https://www.libssh.org/files/0.11/libssh-0.11.1.tar.xz
        tar -xf libssh-0.11.1.tar.xz

    - name: Build libssh
      run: |
        cd libssh-0.11.1
        mkdir build && cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 ..
        make
