name: Build Dropbear for Android ARMv8a

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-dropbear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool wget unzip sed coreutils

      - name: Download and extract Dropbear source
        run: |
          wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2024.86.tar.bz2
          tar xjf dropbear-2024.86.tar.bz2
          mv dropbear-2024.86 dropbear

      - name: Download and set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r25c
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Create localoptions.h to disable password authentication
        run: |
          echo "#ifndef LOCALOPTIONS_H" > dropbear/localoptions.h
          echo "#define LOCALOPTIONS_H" >> dropbear/localoptions.h
          echo "#define DROPBEAR_SVR_PASSWORD_AUTH 0" >> dropbear/localoptions.h
          echo "#define DROPBEAR_CLI_PASSWORD_AUTH 0" >> dropbear/localoptions.h
          echo "#endif /* LOCALOPTIONS_H */" >> dropbear/localoptions.h
          chmod 644 dropbear/localoptions.h  # Ensure correct file permissions

      - name: Configure Dropbear for Android
        run: |
          cd dropbear
          ./configure --host=aarch64-linux-android --enable-static --disable-zlib --disable-password-auth
        env:
          ANDROID_NDK_HOME: $PWD/android-ndk-r25c
          PATH: $PWD/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Build Dropbear
        run: |
          cd dropbear
          make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" STATIC=1
        env:
          ANDROID_NDK_HOME: $PWD/android-ndk-r25c
          PATH: $PWD/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Verify Build Outputs
        run: |
          ls -l dropbear/dropbear
          ls -l dropbear/dbclient
          ls -l dropbear/dropbearkey
          ls -l dropbear/dropbearconvert
          ls -l dropbear/scp

      - name: List files in dropbear directory
        run: |
          ls -l dropbear

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dropbear-android-armv8a
          path: |
            dropbear/dropbear
            dropbear/dbclient
            dropbear/dropbearkey
            dropbear/dropbearconvert
            dropbear/scp
          if-no-files-found: warn
          include-hidden-files: false
