name: Build Dropbear for Android ARMv8a

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-dropbear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool wget unzip

      - name: Download and extract Dropbear source
        run: |
          wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2024.86.tar.bz2
          tar xjf dropbear-2024.86.tar.bz2
          mv dropbear-2024.86 dropbear

      - name: Download and set up Android NDK (r27c)
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r27c
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Check if clang exists
        run: |
          if [ -f "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-unknown-linux-android21-clang" ]; then
            echo "Clang compiler found!"
          else
            echo "Clang compiler not found!"
            exit 1
          fi

      - name: Create localoptions.h to disable password authentication
        run: |
          echo "#ifndef LOCALOPTIONS_H" > dropbear/localoptions.h
          echo "#define LOCALOPTIONS_H" >> dropbear/localoptions.h
          echo "#define DROPBEAR_SVR_PASSWORD_AUTH 0" >> dropbear/localoptions.h
          echo "#define DROPBEAR_CLI_PASSWORD_AUTH 0" >> dropbear/localoptions.h
          echo "#endif /* LOCALOPTIONS_H */" >> dropbear/localoptions.h

      - name: Configure Dropbear for Android ARMv8a using clang
        run: |
          cd dropbear
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-unknown-linux-android21-clang
          export CFLAGS="$CFLAGS -D__ARM_ARCH_8A__ -D__ARM64__ -fPIC -fPIE"
          export LDFLAGS="$LDFLAGS -Wl,--fix-cortex-a53-843419"
          ./configure --host=aarch64-unknown-linux-android --enable-static --disable-zlib

      - name: Build Dropbear for ARMv8a
        run: |
          cd dropbear
          make clean
          make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" STATIC=1

      - name: List files in dropbear directory
        run: |
          ls -l dropbear

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dropbear-android-armv8a
          path: |
            dropbear/dropbear
            dropbear/dbclient
            dropbear/dropbearkey
            dropbear/dropbearconvert
            dropbear/scp
          if-no-files-found: warn
          include-hidden-files: false
