name: Build libssh for Android armv8a

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          tar \
          build-essential \
          cmake \
          python3 \
          clang \
          pkg-config

    - name: Download NDK r27c
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip -O /tmp/android-ndk-r27c.zip
        unzip /tmp/android-ndk-r27c.zip -d $HOME/
        echo "NDK=$HOME/android-ndk-r27c" >> $GITHUB_ENV

    - name: Extract libssh source code
      run: |
        wget https://www.libssh.org/files/0.11/libssh-0.11.1.tar.xz
        tar -xvf libssh-0.11.1.tar.xz
        cd libssh-0.11.1

    - name: Configure build
      run: |
        cd libssh-0.11.1
        mkdir build
        cd build
        $HOME/android-ndk-r27c/ndk-build --target-platform=android-21 --arch=arm64-v8a

    - name: Build libssh
      run: |
        cd libssh-0.11.1/build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=$HOME/android-ndk-r27c/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=21
        make -j$(nproc)

    - name: Archive build artifacts
      run: |
        mkdir -p $GITHUB_ENV
        cp -r libssh-0.11.1/build/* $GITHUB_ENV
