name: Build Dropbear for Android ARMv8a

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-dropbear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool wget unzip

      - name: Download and extract Dropbear source
        run: |
          wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2024.86.tar.bz2
          tar xjf dropbear-2024.86.tar.bz2
          mv dropbear-2024.86 dropbear

      - name: Download and set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r25c
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

      - name: Configure and build Dropbear
        env:
          TOOLCHAIN: ${{ runner.temp }}/android-toolchain
        run: |
          # 设置交叉编译工具链的路径
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
          export AR=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar
          export LD=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld
          export STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip

          # 编译 Dropbear
          cd dropbear
          ./configure --host=aarch64-linux-android --enable-static --disable-zlib
          make PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" STATIC=1

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dropbear-android-armv8a
          path: dropbear/{dropbear,dbclient,dropbearkey,dropbearconvert,scp}
