name: Compile libssh for Android ARMv8a

on:
  # 手动触发工作流
  workflow_dispatch:
  # 在推送到 main 分支时触发工作流
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout 代码
    - name: Checkout code
      uses: actions/checkout@v3  # 使用 actions/checkout@v3 最新版本

    # 安装 Android NDK
    - name: Install Android NDK
      run: |
        # 安装 JDK
        sudo apt update
        sudo apt install -y openjdk-8-jdk

        # 下载并解压 Android NDK (使用最新版本)
        NDK_VERSION="25.2.9519653"  # 更新为你需要的版本
        NDK_URL="https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip"
        wget $NDK_URL
        unzip android-ndk-${NDK_VERSION}-linux.zip
        sudo mv android-ndk-${NDK_VERSION} /usr/local/android-ndk
        echo "ANDROID_NDK=/usr/local/android-ndk" >> $GITHUB_ENV

    # 安装构建依赖
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          wget \
          tar \
          cmake \
          git \
          unzip \
          libssl-dev

    # 下载并解压 libssh
    - name: Download and extract libssh
      run: |
        wget https://www.libssh.org/files/0.11/libssh-0.11.1.tar.xz
        tar -xf libssh-0.11.1.tar.xz
        cd libssh-0.11.1

    # 编译 libssh for ARMv8a
    - name: Build libssh for ARMv8a
      run: |
        mkdir -p build
        cd build
        # 设置交叉编译工具链
        cmake ../ \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DANDROID_NDK=$ANDROID_NDK \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build . --target install

    # 归档编译后的产物
    - name: Archive libssh for ARMv8a
      run: |
        cd build
        tar -czf libssh-arm64-v8a.tar.gz .
        # 可以将构建的文件上传到 GitHub Releases 或其他存储
        echo "Build completed and archived."
