name: Build Telnet Server for Android ARMv8a

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" | sudo tee -a /etc/environment
        source /etc/environment
        java -version

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: '12266719'  # 使用适当版本的 cmdline-tools
        accept-android-sdk-licenses: true  # 自动接受 Android SDK 许可证
        log-accepted-android-sdk-licenses: true
        packages: 'platform-tools, tools'  # 安装所需的 SDK 工具

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          make \
          build-essential \
          automake \
          autoconf \
          libtool \
          pkg-config \
          clang \
          libssl-dev \
          libncurses5-dev \
          zlib1g-dev

    - name: Clone inetutils repository
      run: |
        git clone https://git.savannah.gnu.org/git/inetutils.git
        cd inetutils
        ./bootstrap

    - name: Configure build for Android ARMv8a
      run: |
        cd inetutils
        ./configure --host=aarch64-linux-android --prefix=/tmp/inetutils-android

    - name: Build Telnet for Android ARMv8a
      run: |
        cd inetutils
        make
        make install

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name: inetutils-android
        path: /tmp/inetutils-android
