name: Build Telnet Server for Android ARMv8a

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install JDK 17
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
        sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" | sudo tee -a /etc/environment
        source /etc/environment
        java -version

    - name: Download Android SDK Command-line Tools
      run: |
        # Download and unzip the Android SDK command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip
        sudo mkdir -p /usr/local/android-sdk/cmdline-tools
        sudo unzip -q commandlinetools-linux-12266719_latest.zip -d /usr/local/android-sdk/cmdline-tools

    - name: Set up Android SDK environment variables
      run: |
        echo "export ANDROID_SDK_ROOT=/usr/local/android-sdk" | sudo tee -a /etc/environment
        echo "export PATH=\$PATH:/usr/local/android-sdk/cmdline-tools/latest/bin:/usr/local/android-sdk/platform-tools" | sudo tee -a /etc/environment
        source /etc/environment
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "PATH: $PATH"

    - name: Manually download and install required Android SDK components
      run: |
        # Manually download platform tools, build tools, and platforms
        wget https://dl.google.com/android/repository/platform-tools_r30.0.5-linux.zip
        sudo unzip -q platform-tools_r30.0.5-linux.zip -d /usr/local/android-sdk/
        wget https://dl.google.com/android/repository/build-tools_r30.0.3-linux.zip
        sudo unzip -q build-tools_r30.0.3-linux.zip -d /usr/local/android-sdk/

        # Download and install Android 30 platform
        wget https://dl.google.com/android/repository/platforms/android-30_r05.zip
        sudo unzip -q android-30_r05.zip -d /usr/local/android-sdk/platforms/

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          make \
          build-essential \
          automake \
          autoconf \
          libtool \
          pkg-config \
          clang \
          libssl-dev \
          libncurses5-dev \
          zlib1g-dev

    - name: Clone inetutils repository
      run: |
        git clone https://git.savannah.gnu.org/git/inetutils.git
        cd inetutils
        ./bootstrap

    - name: Configure build for Android ARMv8a
      run: |
        cd inetutils
        ./configure --host=aarch64-linux-android --prefix=/tmp/inetutils-android

    - name: Build Telnet for Android ARMv8a
      run: |
        cd inetutils
        make
        make install

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v3
      with:
        name: inetutils-android
        path: /tmp/inetutils-android
