name: Build Dropbear for ARM

on:
  workflow_dispatch: # 手动触发工作流
    inputs:
      build_type:
        description: "Specify the build type (default: release)"
        required: false
        default: "release"

jobs:
  build:
    name: Build Dropbear
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          curl \
          patch \
          gcc \
          binutils

    - name: Download and extract Dropbear source
      run: |
        curl -L "https://github.com/mkj/dropbear/archive/DROPBEAR_2018.76.tar.gz" | tar xz
        cd dropbear-DROPBEAR_2018.76/
        curl -OL "https://raw.githubusercontent.com/ubiquiti/dropbear-android/master/android-compat.patch"
        curl -OL "https://raw.githubusercontent.com/ubiquiti/dropbear-android/master/config.guess"
        curl -OL "https://raw.githubusercontent.com/ubiquiti/dropbear-android/master/config.sub"

    - name: Update Autotools configuration
      run: |
        cd dropbear-DROPBEAR_2018.76/
        autoupdate || true
        autoreconf -fi

    - name: Apply patch and configure
      run: |
        cd dropbear-DROPBEAR_2018.76/
        patch -p1 < android-compat.patch || (cat configure.rej && exit 1)
        ./configure --host=aarch64-unknown-linux-android \
                    --disable-utmp \
                    --disable-wtmp \
                    --disable-utmpx \
                    --disable-zlib \
                    --disable-syslog

    - name: Build Dropbear
      run: |
        cd dropbear-DROPBEAR_2018.76/
        make LDFLAGS=-static -j$(nproc)
        cp dropbear dropbearkey dropbearconvert dbclient ..
        aarch64-unknown-linux-android-strip dropbear dropbearkey dropbearconvert dbclient

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dropbear-binaries
        path: |
          dropbear
          dropbearkey
          dropbearconvert
          dbclient
